language: c

compiler:
  - clang
  - gcc

before_script:
- sudo apt-get update -qq
- sudo apt-get install -qq cmake python python-dev liblua5.2-dev ruby ruby-dev libperl-dev tcl-dev default-jdk
- curl --silent https://codeload.github.com/ARMmbed/mbedtls/tar.gz/polarssl-1.3.9 | tar xfz - && cd mbedtls-polarssl-1.3.9 && make SHARED=1 && sudo make install DESTDIR=/usr && cd ..

script: cmake . -DDEBUG=on && make && make clean && cmake . -DDEBUG=off && make

after_script: ./proxenet --help

notifications:
  email:
    recipients:
      - hugsy+github@pyc.li

    on_success: always
    on_failure: always
